INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (1, '회사', 'company', 0.1000, 1, 0, NULL);
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (2, '주주', 'partner', 0.0500, 1, 0, NULL);
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (3, '대리', 'agents', 0.1000, 1, 0, NULL);
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (4, '기금회사 abc', 'group', 0.0200, 1, 1, '1234567890');
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (5, '기금회사 xyz', 'group', 0.0200, 1, 1, '1234567890');
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (6, '기금회사 xyz', 'group', 0.0200, 1, 1, '1234567890');
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (7, '1차 추천인', 'recommend_1', 0.0500, 1, 2, NULL);
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (8, '2차 추천인', 'recommend_2', 0.0450, 1, 2, NULL);
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (13, '3차 추천인', 'recommend_3', 0.0400, 1, 2, NULL);
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (14, '4차 추천인', 'recommend_4', 0.0350, 1, 2, NULL);
INSERT INTO `profit_setting`(`ps_id`, `ps_title`, `ps_type`, `ps_profit`, `ps_enabled`, `ps_level`, `ps_phonenumber`) VALUES (15, '5차 추천인', 'recommend_5', 0.0300, 1, 2, NULL);
